### PR TITLE
[MNT] Dropped black formatter

### LINKED ISSUE #36: [ENH] Drop black for ruff embedded formatter.
**Is your feature request related to a problem? Please describe.**
FYI *ruff* now includes a formatter faster than black and with very similar behavior.

**Describe the solution you'd like**
Drop black in favor of ruff to slim skfolio's optional-dependencies.

**Additional context**
a format step could be added to the tests job to warn if code is not properly formatted.

### PR DESCRIPTION
**Pull request by vacarme**
#### Reference Issues/PRs
Fixes #36.

#### What does this implement/fix? Explain your changes.
+ Dropped *black* formatter for *ruff* embedded formatter.
+ Added a format step to the CI *tests* job.

#### Does your contribution introduce a new dependency? If yes, which one?
[-] black

#### What should a reviewer concentrate their feedback on?

if accepted, make a branch with formatted code and merge it to main.

#### Did you add any tests for the change?

no

### CODE REVIEW

**Comment by vacarme** [comment]
As you can see the CI did not pass because the code format is not ok.
If you're in favor of dropping black, next step will be to run `ruff format`, commit all files and merge this pr.

**Review by HugoDelatte — CHANGES_REQUESTED** [review]
I agree, the ruff formatting is very close to Black so we can drop the Back dependency.
Can you just add "ISC001" in `ignore = ["E203", "E501", "ISC001"]` as specified by Ruff as it may create conflict apparently.
Also, if you include the reformatted files using `ruff format` directly in this PR, it should work I think.
Thank you for your contribution, it's much appreciated!

**Comment by vacarme** [comment]
+ removed ruff redundant rules when using ruff formatter which are for skfolio :
    + "ISC001", 
    + "ISC002"
    +  "E111"
    +  "E114"
    + "E117"
+ formatted all the code with ruff formatter (10 files impacted with minimal changes):
    + measures/_enums.py
    + model_selection/_combinatorial.py
    + model_selection/_validation.py
    + optimization/_base.py
    + optimization/convex/_mean_risk.py
    + optimization/ensemble/_stacking.py
    + population/_population.py
    + portfolio/_portfolio.py
    + prior/_factor_model.py
    + utils/fixes/_dendrogram.py
+ solved the line-length discrepancy. Previously **E501** was ignored whereas a line-length was specified in the `[tool.ruff]` section. My guess is this was a way of avoiding ruff's many warnings on docstrings length. So I added `[tool.ruff.lint.pycodestyle]` section to disable the linter warnings and kept `line-length` to be used by the formatter.

**Review by HugoDelatte — APPROVED** [review]
Looks good, the line length solution is great. Thx for the PR!

**Pull request merged**
